create_GKE.yaml

diff --git a/.github/workflows/create_GKE.yaml b/.github/workflows/create_GKE.yaml
--- a/.github/workflows/create_GKE.yaml
+++ b/.github/workflows/create_GKE.yaml
@@ -1,12 +1,15 @@
-name: Terraform GKE Deploy
+name: Terraform K8S Deploy
 
 on:
-  #push:
-  #  branches:
-  #    - main
-  #pull_request:
   workflow_dispatch:
     inputs:
+      cloud:
+        description: "Cloud"
+        required: true
+        type: choice
+        options:
+          - AWS
+          - GCP
       environment:
         description: "Target environment"
         required: true
@@ -16,7 +19,7 @@ on:
           - staging
           - prod
       cluster_name:
-        description: "GKE cluster name (only lowercase letters, numbers, and hyphens. Must start with a lowercase letter)"
+        description: "K8S cluster name (only lowercase letters, numbers, and hyphens. Must start with a lowercase letter)"
         required: true
         type: string
 
@@ -29,7 +32,7 @@ env:
   PROJECT_ID: ${{ vars.PROJECT_ID}}
   TF_VAR_project_id: ${{ vars.PROJECT_ID}}
   TF_VAR_region: ${{ vars.REGION }}
-  ENVIRONMENT: ${{ github.event.inputs.environment }}
+  ENVIRONMENT: ${{ inputs.environment }}
 
 jobs:
   terraform:
@@ -44,12 +47,12 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Validate GKE cluster name
+      - name: Validate K8S cluster name
         run: |
           NAME="${{ inputs.cluster_name }}"
 
           if [[ ! "$NAME" =~ ^[a-z]([-a-z0-9]{0,38}[a-z0-9])?$ ]]; then
-            echo "❌ Invalid GKE cluster name"
+            echo "❌ Invalid K8S cluster name"
             echo "Rules:"
             echo " - 1–40 characters"
             echo " - lowercase letters, numbers, hyphens"
@@ -58,14 +61,14 @@ jobs:
             exit 1
           fi
 
-          echo "✅ GKE cluster name is valid: $NAME"
+          echo "✅ K8S cluster name is valid: $NAME"
 
       - name: Authenticate to Google Cloud (WIF)
         uses: google-github-actions/auth@v3
         with:
           project_id: ${{ env.PROJECT_ID }}
           workload_identity_provider: projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
-          service_account: github-terraform@chatgpt1-goland1.iam.gserviceaccount.com
+          service_account: github-terraform-k8s@${{vars.PROJECT_ID}}.iam.gserviceaccount.com
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
@@ -77,6 +80,11 @@ jobs:
           echo "Repository: $GITHUB_REPOSITORY"
           echo "Ref: $GITHUB_REF"
 
+      - name: Stop workflow
+        run: |
+          echo "Intentional stop"
+          exit 1
+######################################
       - name: Terraform Init
         run: |
           terraform init \
@@ -92,10 +100,6 @@ jobs:
             -var-file="./envs/${{ inputs.environment }}.tfvars" \
             -out=tfplan
 
-      - name: Stop workflow
-        run: |
-          echo "Intentional stop"
-          exit 1
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main'
@@ -109,7 +113,7 @@ jobs:
       - name: Set up gcloud
         uses: google-github-actions/setup-gcloud@v2
 
-      - name: Get GKE credentials
+      - name: Get K8S credentials
         run: |
           gcloud container clusters get-credentials \
             ${{ inputs.cluster_name }} \
