update Deploy Cluster Tools

diff --git a/.github/workflows/deploy_cluster_tools.yml b/.github/workflows/deploy_cluster_tools.yml
--- a/.github/workflows/deploy_cluster_tools.yml
+++ b/.github/workflows/deploy_cluster_tools.yml
@@ -15,21 +15,39 @@ on:
           - dev
           - staging
           - prod
-      cluster_name:
-        description: "GKE cluster name (only lowercase letters, numbers, and hyphens. Must start with a lowercase letter)"
+      env_type:
+        description: "Environment type"
         required: true
-        type: string
+        type: choice
+        options:
+          - dev
+          - staging
+          - prod
+      env_number:
+        description: "K8S environment (cluster) number (e.g. 1 or 01 for dev-01, 2 or 02 for dev-02)"
+        required: true
+        type: string          
+#      cluster_name:
+#        description: "GKE cluster name (only lowercase letters, numbers, and hyphens. Must start with a lowercase letter)"
+#        required: true
+#        type: string
 
 permissions:
   contents: read
   id-token: write   # REQUIRED for Workload Identity Federation
 
 env:
-  PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
-  PROJECT_ID: ${{ vars.PROJECT_ID}}
+#  PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
+#  PROJECT_ID: ${{ vars.PROJECT_ID}}
+#  TF_VAR_project_id: ${{ vars.PROJECT_ID}}
+#  TF_VAR_region: ${{ vars.REGION }}
+#  ENVIRONMENT: ${{ github.event.inputs.environment }}
   TF_VAR_project_id: ${{ vars.PROJECT_ID}}
   TF_VAR_region: ${{ vars.REGION }}
-  ENVIRONMENT: ${{ github.event.inputs.environment }}
+  TF_VAR_runner_service_account: ${{ vars.runner_service_account}}
+  TF_VAR_env_type: ${{ inputs.env_type }}
+  TF_VAR_env_number: ${{inputs.env_number}}
+
 
 jobs:
   terraform:
@@ -41,15 +59,16 @@ jobs:
         working-directory: terraform/gcp
 
     steps:
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Validate GKE cluster name
+      - name: Validate K8S environment (cluster) name
         run: |
-          NAME="${{ inputs.cluster_name }}"
+          env_name="${{inputs.env_type}}-${{inputs.env_number}}"
 
-          if [[ ! "$NAME" =~ ^[a-z]([-a-z0-9]{0,38}[a-z0-9])?$ ]]; then
-            echo "❌ Invalid GKE cluster name"
+          if [[ ! "$env_name" =~ ^[a-z]([-a-z0-9]{0,38}[a-z0-9])?$ ]]; then
+            echo "❌ Invalid K8S cluster name"
             echo "Rules:"
             echo " - 1–40 characters"
             echo " - lowercase letters, numbers, hyphens"
@@ -58,41 +77,96 @@ jobs:
             exit 1
           fi
 
-          echo "✅ GKE cluster name is valid: $NAME"
+          echo "✅ K8S cluster name is valid: $env_name"
 
       - name: Authenticate to Google Cloud (WIF)
         uses: google-github-actions/auth@v3
         with:
-          project_id: ${{ env.PROJECT_ID }}
-          workload_identity_provider: projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
-          service_account: github-terraform@chatgpt1-goland1.iam.gserviceaccount.com
-      
+          project_id: ${{ vars.PROJECT_ID }}
+          workload_identity_provider: projects/${{vars.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
+          service_account: ${{vars.runner_service_account}}@${{vars.PROJECT_ID}}.iam.gserviceaccount.com
+
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: 1.14
-      
+
       - name: Debug OIDC token
         run: |
           echo "Repository: $GITHUB_REPOSITORY"
           echo "Ref: $GITHUB_REF"
-      
+
       - name: Terraform Init
         run: |
           terraform init \
-            -backend-config="prefix=envs/${{ inputs.environment }}/${{ inputs.cluster_name }}"
+            -backend-config="prefix=${{ inputs.env_type }}/${{ inputs.env_number }}"
+
+
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#
+#      - name: Validate GKE cluster name
+#        run: |
+#          NAME="${{ inputs.cluster_name }}"
+#
+#          if [[ ! "$NAME" =~ ^[a-z]([-a-z0-9]{0,38}[a-z0-9])?$ ]]; then
+#            echo "❌ Invalid GKE cluster name"
+#            echo "Rules:"
+#            echo " - 1–40 characters"
+#            echo " - lowercase letters, numbers, hyphens"
+#            echo " - must start with a letter"
+#            echo " - must not end with a hyphen"
+#            exit 1
+#          fi
+#
+#          echo "✅ GKE cluster name is valid: $NAME"
+#
+#      - name: Authenticate to Google Cloud (WIF)
+#        uses: google-github-actions/auth@v3
+#        with:
+#          project_id: ${{ env.PROJECT_ID }}
+#          workload_identity_provider: projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
+#          service_account: github-terraform@chatgpt1-goland1.iam.gserviceaccount.com
+#      
+#      - name: Set up Terraform
+#        uses: hashicorp/setup-terraform@v3
+#        with:
+#          terraform_version: 1.14
+#      
+#      - name: Debug OIDC token
+#        run: |
+#          echo "Repository: $GITHUB_REPOSITORY"
+#          echo "Ref: $GITHUB_REF"
+#      
+#      - name: Terraform Init
+#        run: |
+#          terraform init \
+#            -backend-config="prefix=envs/${{ inputs.environment }}/${{ inputs.cluster_name }}"
 
       - name: Set up gcloud
         uses: google-github-actions/setup-gcloud@v2
         with:
           install_components: gke-gcloud-auth-plugin
-
-      - name: Get GKE credentials
+          
+      - name: Get K8S credentials
         run: |
           gcloud container clusters get-credentials \
-            ${{ inputs.cluster_name }} \
-            --location $(terraform output -raw location) \
-            --project ${{ env.PROJECT_ID }}
+            ${{inputs.env_type}}-${{inputs.env_number}} \
+            --location $(terraform output -raw cluster_location) \
+            --project ${{ vars.PROJECT_ID }}
+
+
+#      - name: Set up gcloud
+#        uses: google-github-actions/setup-gcloud@v2
+#        with:
+#          install_components: gke-gcloud-auth-plugin
+#
+#      - name: Get GKE credentials
+#        run: |
+#          gcloud container clusters get-credentials \
+#            ${{ inputs.cluster_name }} \
+#            --location $(terraform output -raw location) \
+#            --project ${{ env.PROJECT_ID }}
       
       #- run: gcloud components list
 
